### ISSUE TITLE
Improve style

### ISSUE THREAD

**Issue by ggarnier** [tsuru/tsuru-autoscale-dashboard#4]
The autoscale form is really ugly. It really needs some updates, like styling the add/remove/update buttons and adding spacing in the form fields.

**Comment by Sando1** [comment]
Hi, will be working on this issue. :)

**Comment by Sando1** [comment]
So I am having trouble with starting the app. I run the make run command and this is the error:
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7feac3a1d598>
Traceback (most recent call last):
  File "../Python/dashboard/lib/python3.5/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "../Python/dashboard/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 121, in inner_run
    self.check(display_num_errors=True)
  File "../Python/dashboard/lib/python3.5/site-packages/django/core/management/base.py", line 374, in check
    include_deployment_checks=include_deployment_checks,
  File "../Python/dashboard/lib/python3.5/site-packages/django/core/management/base.py", line 361, in _run_checks
    return checks.run_checks(**kwargs)
  File "../Python/dashboard/lib/python3.5/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "../Python/dashboard/lib/python3.5/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "../Python/dashboard/lib/python3.5/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    for pattern in resolver.url_patterns:
  File "../Python/dashboard/lib/python3.5/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "../Python/dashboard/lib/python3.5/site-packages/django/urls/resolvers.py", line 313, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "../Python/dashboard/lib/python3.5/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "../Python/dashboard/lib/python3.5/site-packages/django/urls/resolvers.py", line 306, in urlconf_module
    return import_module(self.urlconf_name)
  File "../Python/dashboard/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 985, in _gcd_import
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 957, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 697, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "../Python/dashboard/tsuru-autoscale-dashboard/dashboard/urls.py", line 5, in <module>
    url(r'^', include('tsuru_dashboard.urls')),
  File "../Python/dashboard/lib/python3.5/site-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "../Python/dashboard/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 985, in _gcd_import
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 957, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 697, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "../Python/dashboard/lib/python3.5/site-packages/tsuru_dashboard/urls.py", line 7, in <module>
    url(r'^admin/', include('tsuru_dashboard.admin.urls')),
  File "../Python/dashboard/lib/python3.5/site-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "../Python/dashboard/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 985, in _gcd_import
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 957, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 697, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "../Python/dashboard/lib/python3.5/site-packages/tsuru_dashboard/admin/urls.py", line 4, in <module>
    import views
ImportError: No module named 'views'

**Comment by ggarnier** [comment]
This project is really old, I think it doesn't work with python 3. Could you try with python 2.7?

**Comment by Sando1** [comment]
Still having issues. Here's what I did:
1. Cloned the repository
2. Created a virtual environment
3. Fixed all dependency issues (i need python 2 only) 
4. Migrated the database 
5. Run server.
However, when i run server, i get a 401 error. Are there any settings I need to change?

**Comment by orafaelfragoso** [comment]
@ggarnier I need a `TSURU_TOKEN` or instructions on how to set it. Without it, I can't login or navigate through the interface.

I tried removing the auth middleware but all services are using this token to query the DB.

Can you help?

**Comment by ggarnier** [comment]
@orafaelfragoso First you need to run tsuru API. Check the docs for running it with [tsuru installer](https://docs.tsuru.io/stable/installing/using-tsuru-installer.html) or [docker compose](https://docs.tsuru.io/stable/contributing/compose.html). Then you can [create a token](https://docs.tsuru.io/stable/using/team-tokens.html) to make requests to the API.
